spring:
  application:
    name: cellophane

server:
  port: ${CELLOPHANE_HTTP_PORT:8025}

cellophane:
  smpp-port: ${CELLOPHANE_SMPP_PORT:2775}
  accounts: ${CELLOPHANE_ACCOUNTS:cellophane:cellophane}
  max-messages: ${CELLOPHANE_MAX_MESSAGES:10000}

springdoc:
  api-docs:
    path: /api/openapi.json
  swagger-ui:
    path: /api

logging:
  level:
    io.cellophane: info
