[versions]
java = "21"
springBoot = "4.1.1"
springdoc = "3.1.0"
netty = "4.2.17.Final"
junit = "6.1.3"
assertj = "3.27.7"
sqliteJdbc = "3.53.4.0"
nodeGradle = "7.1.0"
node = "22.15.1"

[libraries]
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }
netty-codec = { module = "io.netty:netty-codec" }
netty-handler = { module = "io.netty:netty-handler" }
netty-transport = { module = "io.netty:netty-transport" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
springdoc-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
node = { id = "com.github.node-gradle.node", version.ref = "nodeGradle" }
